import { WapperMenu } from '@/components/sideMenu';
import { DialogProvider } from '@/contexts/DialogContext';
import QueryProvider from '@/contexts/QueryContext';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import '../styles/globals.scss';
import { GlobalProvider } from '@/contexts/GlobalContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-BR' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <QueryProvider>
          <DialogProvider>
            <GlobalProvider>
              <ToastContainer theme='colored' />
              <WapperMenu>{children}</WapperMenu>
            </GlobalProvider>
          </DialogProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
